### ISSUE TITLE
 paper-chip-input-autocomplete remove item not working correctly

### ISSUE THREAD

**Issue by kmyllyvi** [ThomasCybulski/paper-chip#17]
Hi.
First of all thanks for a great element for polymer2. I’m wondering if I’m missing something or is there a bug removing a chip on paper-chip-input-autocomplete.html. I dug in a bit and noticed that on-chip-removed was not called. Traced the issue to the id of the element “slot” where paper-chip sends an event when id == “slot2”. If change this it works.
See:

paper-chip.html
`_remove(event) {   if (this.parentNode.id == 'slot2') { …`

paper-chip-input-autocomplete.html
`<paper-input id="paperInput" label="[[label]]" on-keyup="_findItems" on-keydown="_keydown" value="{{_inputValue}}" autofocus>     <slot id="slot" name="input" slot="prefix">`

Thanks.

**Comment by ThomasCybulski** [comment]
Hi,

yes you're right, that's a bug. I'm currently working on it and I hope I can fix it soon.

**Comment by kmyllyvi** [comment]
Thanks. If I may suggest couple of improvements:
* possibility to have avatar/icon also on autocomplete item
* make minSearchStringLength configurable OR rather 1-char, instead of 2 by default? There's often not that many users and would be good to see the list with typing just one char
Cheers.

**Comment by kmyllyvi** [comment]
Hi.
I hope you accept my fix and change request and can do a new version. thnx.

**Comment by ThomasCybulski** [comment]
> make minSearchStringLength configurable OR rather 1-char, instead of 2 by default? 

The min search length is a public property of the custom element and can be overwritten with e.g. 
`min-search-string-length="1"`
