### ISSUE TITLE
paper-chip-input-autocomplete doesn't work on Safari or Firefox (on Mac)

### ISSUE THREAD

**Issue by kmyllyvi** [ThomasCybulski/paper-chip#21]
Tested the demo on MacOS (10.12.) Safari / Firefox (latest versions). Search results are not displayed at all.

**Comment by ThomasCybulski** [comment]
Indeed, there is a bug in the demo page, thanks! I will fix this for Safari. 
Firefox has a few more problems with the polyfills. Actually, I don't know if I can fix it soon.

**Comment by ThomasCybulski** [comment]
#22 fixed
