### ISSUE TITLE
Conflict with all the existing iron icons

### ISSUE THREAD

**Issue by prateeklal** [ThomasCybulski/paper-chip#27]
When I tried installing it using `bower install --save ThomasCybulski/paper-chip`, it removed all the iron icons present in my application. Upon uninstallation, it started to display fine.

**Comment by ThomasCybulski** [comment]
Hi, can you please put your code in jsfiddle? 
Because I tried exactly what you said, but I can't reproduce the problem.
https://jsfiddle.net/b0x1rkzb/

**Comment by prateeklal** [comment]
I tried it again and it worked. Couldn't figure out what was the problem initially. Thanks anyway.
