### ISSUE TITLE
Firefox 54 supports this element

### ISSUE THREAD

**Issue by NicolaiSchmid** [ThomasCybulski/paper-chip#30]
I've tested this element with Firefox Version 54, and all basic functionality seems to be available.

**Comment by ThomasCybulski** [comment]
I got some styling issues and an error in webcomponent-lite.js

![paper-chip-mozilla](https://user-images.githubusercontent.com/7078705/28860162-9a21d4a4-775b-11e7-852f-9a0ad5e01552.png)

**Comment by NicolaiSchmid** [comment]
Your're right, using the demo/index.html I get the same error.
On my page however, using just the element itself `<paper-chip label="Description"></paper-chip>` I don't get any errors. Probably the error occurs in some of the advanced features.
But it would be better to leave it as unsupported until the issue is resolved
