### ISSUE TITLE
Styles Broken on Non-Chrome Browsers

### ISSUE THREAD

**Issue by first87** [ThomasCybulski/paper-chip#32]
Currently `paper-chip` looks okay on Chrome, but looks ugly on other browsers:
 * styled incorrectly ~ seemed unstyled
 * icon right-aligned (different with Chrome)

I ran the demo from the webcomponents.org:
https://www.webcomponents.org/element/ThomasCybulski/paper-chip/demo/demo/index.html

Here are some screenshots:
* Firefox:
![image](https://user-images.githubusercontent.com/20905447/29348240-fbb9354e-8206-11e7-84b6-57da55d6e028.png)
* Edge:
![image](https://user-images.githubusercontent.com/20905447/29348500-1e09d700-8209-11e7-8e35-f87aafbd48e3.png)
* IE 11:
![image](https://user-images.githubusercontent.com/20905447/29348484-f5c7f844-8208-11e7-9c3a-8fd805fab543.png)

Could you manage this issue?

Thank you.

**Comment by ThomasCybulski** [comment]
Hi, yes thats right. It's a problem with webcomponentjs. 
I will take a look at it

**Comment by first87** [comment]
@ThomasCybulski  Thank you for the update.
In the meanwhile, I tried to resolve this issue myself and so I have found two main problems:

* The first one is that `slot` was styled inproperly on `paper-chip.html`. 
  I already fixed the first problem and created a PR: https://github.com/ThomasCybulski/paper-chip/pull/33.

* The second one seems related with `dom-repeat`, meaning that `dom-repeat`, used in `paper-chip-input.html#L60` and `paper-chip-input-autocomplete.html#L98`, are not sensitive to changes on `items`.
  I have not resolved the problem yet.

**Comment by ThomasCybulski** [comment]
Many thanks!

#33 is merged

**Comment by first87** [comment]
My pleasure! By the way, did you check 2nd issue I mentioned? It happens on both `paper-chip-input` and `paper-chip-input-autocomplete`.

**Comment by ThomasCybulski** [comment]
Yes, let me reopen this issue and I hope I can spot the problem

**Comment by first87** [comment]
And I found more issues:
3) `items` doesn't work properly on non-Chrome browsers~
  ```html
<paper-chip-input label="+Add (Enter) -Delete (Backspace)" closable items='["one", "two", "three"]'></paper-chip-input>
  ```
  ![image](https://user-images.githubusercontent.com/20905447/29419325-b503dd2a-8323-11e7-9021-ed656d99b936.png)

4) `paper-chip-input-autocomplete` never triggered on any input on IE
  ![image](https://user-images.githubusercontent.com/20905447/29419448-ff6daad0-8323-11e7-9f05-b8cbe4c0d603.png)

**Comment by ThomasCybulski** [comment]
This is a very good feedback!
I will verify this problems on my system and I will open seperate iddues for that.

**Comment by first87** [comment]
Thank you and I hope to get any update for the issues soon.
I will also update if I make any progress to fix any of those 3 issues~
Cheers!

**Comment by BorntraegerMarc** [comment]
@ThomasCybulski maybe we could bring the component to a state where all major browsers (including IE, Edge, Firefox, Safari 8) are supported. As stated in the readme https://github.com/ThomasCybulski/paper-chip#browser-support this component does not really support other major browsers.

I wanted to ask: why is this the case? I don't see any major challenges to implement the functionality on all browsers.

**Comment by first87** [comment]
I just fixed all problems and created new PR #34.

**Comment by ThomasCybulski** [comment]
Thanks @first87 for your support!

**Comment by first87** [comment]
No problem. :)
Thanks @ThomasCybulski for the update.
