### ISSUE TITLE
Focusing autocomplete list with up/down key

### ISSUE THREAD

**Issue by ainvaltin** [ThomasCybulski/paper-chip#43]
It seems that focusing the autocomplete list with up/down key isn't working.

I tested the demo where the last one is "paper-chip's from autocomplete" - there I typed "al" and autocomplete list pops up, but when pressing up or down key then the caret jumps to the beginning or end of the input rather than selecting item in the autocomplete list.

Tested with
Chromium-browser Version 61.0.3163.79 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Google-Chrome Version 60.0.3112.78 (Official Build) (64-bit)

**Comment by ThomasCybulski** [comment]
Hi @ainvaltin 
can you please check the version 2.0.16 and give me an answer if the problem has been solved?

**Comment by ainvaltin** [comment]
Seems to work with "polymer#^v2.1.0"
