### ISSUE TITLE
Multi-line paper-chip-input spills outside it's container

### ISSUE THREAD

**Issue by ainvaltin** [ThomasCybulski/paper-chip#48]
To reproduce make new "polymer-2-starter-kit" application (with the polymer-cli), open the generated "my-view1.html" add `paper-chip-input` as the last tag to the `<div class="card">`. Now open the app in browser and enter several chips to the input until they won't fit onto the single line. The multi line input "spills" over the edge of it's container (see attached picture):

![ci](https://user-images.githubusercontent.com/9789293/31306200-86166976-ab53-11e7-9be0-77427dbfb63e.png)

**Comment by ainvaltin** [comment]
The `paper-chip-input` has in it's `style` height defined for `paper-input`:

    paper-input {
        height:  var(--paper-chip-input-height, 59px);

 It seems that removing that fixes the problem. Haven't tested it extensively though.

**Comment by ThomasCybulski** [comment]
Fixed https://github.com/ThomasCybulski/paper-chip/pull/65
