### ISSUE TITLE
Add support for readonly

### ISSUE THREAD

**Issue by ainvaltin** [ThomasCybulski/paper-chip#55]
Please add `readonly` property / attribute for `paper-chip-input` and `paper-chip-input-autocomplete`.

**Comment by ThomasCybulski** [comment]
Done https://github.com/ThomasCybulski/paper-chip/pull/58

**Comment by ainvaltin** [comment]
When set to `readonly`, it is still possible to remove chips via close button.

**Comment by ThomasCybulski** [comment]
For your case, you can change  the `closable` to false
