### ISSUE TITLE
Allow duplicate entries in paper-chip-input-autocomplete

### ISSUE THREAD

**Issue by ainvaltin** [ThomasCybulski/paper-chip#62]
Add `allow-duplicates` property for `paper-chip-input-autocomplete` which when set would allow to have same chip mote than once in the input. This would also mean that acutocomplete list is not filtered and when `additional-items` is set then same new item can be entered multiple times.

**Comment by ThomasCybulski** [comment]
Fixed https://github.com/ThomasCybulski/paper-chip/pull/66

**Comment by ainvaltin** [comment]
Entering new label more than once works, thanks. But the autocomplete list is filtered, ie one  can't select same item twice via autocomplete list (I can add the same item twice by typing it out the second time)... is that intentional or bug?
