### ISSUE TITLE
paper-chip-input removes two chips on press of backspace in IE

### ISSUE THREAD

**Issue by hitesh153** [ThomasCybulski/paper-chip#70]
When moving through the demo in IE. `paper-input-autocomplete` removes two chips on press of backspace. Also the styles are breaking for the paper-input

**Comment by ThomasCybulski** [comment]
You mean IE or Edge and in which version?

**Comment by hitesh153** [comment]
I’m using IE11 and you can see the demo on webcomponents page. It is
breaking even there.

**Comment by ThomasCybulski** [comment]
Unfortunately, I will not work on any improvements for IE 11. 
But you can contribute to this project and implementing the support for IE.

**Comment by hitesh153** [comment]
Surely, will take a look and generate a PR with the fix.
Thank you!
